name: AWS KVS WebRTC Android SDK CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java: [11, 17]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}

    - name: Download libwebrtc-123.0.0.aar
      run: wget -O app/libs/libwebrtc-123.0.0.aar https://github.com/rno/WebRTC/releases/download/123.0.0/libwebrtc-123.0.0.aar

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test
